1.Crie um array com 4 linhas e 3 colunas com valores aleatórios.

In [1]:
import numpy as np

In [2]:
aleatorio=np.random.random((4,3))
aleatorio

array([[0.45100699, 0.86055423, 0.17039989],
       [0.37451525, 0.01906776, 0.84256179],
       [0.53721606, 0.52548175, 0.48545176],
       [0.53665421, 0.0332825 , 0.82892725]])

2.Crie um array com valores inteiros,3 linhas e 5 colunas com valores aleatórios.

In [3]:
inteiros=np.random.randint(100,size=(3,5))
inteiros

array([[ 4, 54, 91, 50, 50],
       [35, 81, 85, 88, 57],
       [44, 26, 17, 86, 76]])

3.Crie um array com 5 colunas e 10 linhas inicializados com zeros.

In [4]:
zero=np.zeros((5,10))
zero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

4.Crie um array que vá entre 0 e 90 pulando de 4 em 4.

In [5]:
intervalo=np.arange(0,100,4)
intervalo

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

5.Reduza o array (5,7) a apenas uma dimensão.

In [6]:
# criando um array de números aleatórios,com 5 linhas e 7 colunas
reduzido=np.random.randint(100,size=(5,7))
reduzido

array([[13, 68, 96, 91, 58, 60, 72],
       [27, 56, 55, 30, 43, 91, 91],
       [44, 18,  9, 39, 86, 28, 74],
       [69, 35, 16, 24, 78, 50, 55],
       [30, 76, 53, 13, 69, 72, 38]])

In [7]:
# reduzindo o array a apenas uma dimensão
reduce=reduzido.flatten()
reduce

array([13, 68, 96, 91, 58, 60, 72, 27, 56, 55, 30, 43, 91, 91, 44, 18,  9,
       39, 86, 28, 74, 69, 35, 16, 24, 78, 50, 55, 30, 76, 53, 13, 69, 72,
       38])

6.Considerando que você é uma organizadora de um jogo de bingo. Crie um array que irá representar a cartilha desses jogos de bingo. os números das suas cartelas variam entre 1 e 30, e você terá 10 participantes.Cada cartela terá 12 números (4,3). Crie um array que representa esse jogo.

In [8]:
bingo=np.random.randint(1,31,size=(4,3,10))
bingo

array([[[11,  8, 21,  7, 20, 14,  4, 29,  6, 23],
        [25, 26,  5,  1, 18,  2, 26,  1,  2, 16],
        [23, 26, 10, 29, 11,  1,  5, 28, 30,  1]],

       [[29,  1, 12, 25, 18, 13, 26, 14, 15, 26],
        [30, 11, 12,  4, 11,  3,  5, 10, 12, 10],
        [28, 27, 21,  9,  2, 28, 23, 11, 11, 25]],

       [[ 8,  2, 11, 14, 12,  5,  7, 30,  4,  4],
        [24, 12, 27, 23, 30, 25, 30, 26, 28, 22],
        [ 6, 24, 15, 18, 24, 13, 23,  2,  2, 20]],

       [[20, 14,  7, 15,  7,  9, 12, 30, 27, 15],
        [20,  8, 19,  9,  5, 17, 28, 10, 27, 18],
        [21, 11, 29, 27, 17, 20,  2, 22, 12,  7]]])

7.Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas.

In [9]:
resh=bingo.reshape((5,4,6))
resh

array([[[11,  8, 21,  7, 20, 14],
        [ 4, 29,  6, 23, 25, 26],
        [ 5,  1, 18,  2, 26,  1],
        [ 2, 16, 23, 26, 10, 29]],

       [[11,  1,  5, 28, 30,  1],
        [29,  1, 12, 25, 18, 13],
        [26, 14, 15, 26, 30, 11],
        [12,  4, 11,  3,  5, 10]],

       [[12, 10, 28, 27, 21,  9],
        [ 2, 28, 23, 11, 11, 25],
        [ 8,  2, 11, 14, 12,  5],
        [ 7, 30,  4,  4, 24, 12]],

       [[27, 23, 30, 25, 30, 26],
        [28, 22,  6, 24, 15, 18],
        [24, 13, 23,  2,  2, 20],
        [20, 14,  7, 15,  7,  9]],

       [[12, 30, 27, 15, 20,  8],
        [19,  9,  5, 17, 28, 10],
        [27, 18, 21, 11, 29, 27],
        [17, 20,  2, 22, 12,  7]]])

**Manipulando Arrays**

1.Explorando Ecossistemas: Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo abaixo demonstra dados das espécies encontradas, considere a seguinte ordem de colunas:

**ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie.**



In [10]:
especies=np.array([[747,89,33,5],[623,123,32,13],[501,22,49,2],[116,101,42,10],[297,56,69,22],[613,64,27,7],[295,84,29,14],[692,105,72,16],[229,103,35,5],[374,124,70,1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

a.Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array as qtd_especies.

In [11]:
qtd_especies=especies[:,1]
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

b.De qtd_especies selecione apenas as primeiras 3 quantidades e printe.

In [12]:
print(qtd_especies[:3])

[ 89 123  22]


c.Printe as 5 últimas quantidades de espécies.

In [13]:
print(qtd_especies[-5:])

[ 64  84 105 103 124]


d.Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente.

In [14]:
crescente=np.sort(especies[:,3])
crescente

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

2.Ainda usando o Array de espécies marítimas:

a.Usando um index booleano crie um array que contém os dados da maior espécie encontrada (considerando o seu tamanho), esse valor corresponde ao valor 22.



In [15]:
# criando o index booleano que verifica entre todas as linhas, qual possui a última coluna, que corresponde ao tamano médio, com valor 22, que é o maior tamanho encontrado
index=especies[:,3]==22
index

array([False, False, False, False,  True, False, False, False, False,
       False])

In [16]:
# exibindo a linha que foi filtrada pelo index criado, mostrando todas as informações da espécie (onde linha =True)
maior=especies[index]
maior

array([[297,  56,  69,  22]])

b.Usando fancy index faça um array que contém apenas dados da espécie com ID 297.

In [17]:
esp_297=especies[especies[:,0]==297]
esp_297

array([[297,  56,  69,  22]])

c.Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.

In [18]:
where=especies[np.where(especies[:,1]==105)]
where

array([[692, 105,  72,  16]])

d.Considere a profundeza em que a espécie foi encontrada e substitua valores maiores que 60 com "Profundo”


In [19]:
profundeza=especies.copy()

In [20]:
# transformando o array que era do tipo int em object, para que possa substituir um valor do tipo inteiro, por outro que é string
profundeza = profundeza.astype(object)

In [21]:
# fazendo a filtragem e a substituição, em todas as linhas da coluna de índice 2, onde houver valor maior q 60, será substituído por 'Profundo'
profundeza[profundeza[:, 2] > 60, 2] = 'Profundo'

In [22]:
profundeza

array([[747, 89, 33, 5],
       [623, 123, 32, 13],
       [501, 22, 49, 2],
       [116, 101, 42, 10],
       [297, 56, 'Profundo', 22],
       [613, 64, 27, 7],
       [295, 84, 29, 14],
       [692, 105, 'Profundo', 16],
       [229, 103, 35, 5],
       [374, 124, 'Profundo', 1]], dtype=object)

3.Ainda no conjunto 'especies':

a.Adicione mais 2 espécies ao array: [[204,10,40,12], [392,11,81,11]].

In [23]:
# criando um array com as 2 espécies a serem adicionadas
arr1=np.array([[204,10,40,12],[392,11,81,11]])
arr1

array([[204,  10,  40,  12],
       [392,  11,  81,  11]])

In [24]:
# concatenando os dois arrays pela axis 0, isto é, no eixo horizontal
novas_especies = np.concatenate((especies,arr1), axis=0)
novas_especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

b.Adicione mais uma coluna no array original agora com o número de espécies encontradas com que indica se o animal enxerga ou não: [0,1,0,0,0,0,1,0,1,1,0].

In [25]:
# criando um array
arr2=np.array([0,1,0,0,0,0,1,0,1,1,0,1])

In [26]:
# transformando o array em uma coluna
arr2=arr2.reshape(-1,1)

In [27]:
# concatenando a nova coluna ao array novas_especies
novo_atributo = np.concatenate((novas_especies,arr2), axis=1)
novo_atributo

array([[747,  89,  33,   5,   0],
       [623, 123,  32,  13,   1],
       [501,  22,  49,   2,   0],
       [116, 101,  42,  10,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1],
       [204,  10,  40,  12,   0],
       [392,  11,  81,  11,   1]])

### **Cálculo com Array**

Considerando o array abaixo, responda:

acidentes=np.array([[1,3,2],[0,1,0],[2,1,4],[0,0,0],[1,1,0]])

In [28]:
acidentes=np.array([[1,3,2],[0,1,0],[2,1,4],[0,0,0],[1,1,0]])
acidentes

array([[1, 3, 2],
       [0, 1, 0],
       [2, 1, 4],
       [0, 0, 0],
       [1, 1, 0]])

1.O cliente que teve acidente abaixo da média nos últimos 2 anos, ganhará um desconto no seu seguro. Identifique-os.

In [29]:
# selecionando as duas últimas colunas, considerando que representem os últimos dois anos
colunas=acidentes[:,-2:]
colunas

array([[3, 2],
       [1, 0],
       [1, 4],
       [0, 0],
       [1, 0]])

In [30]:
# calculando a média geral das duas colunas
media=np.mean(colunas)
media

1.2

In [31]:
# fazendo a comparação usando o método all() para comparar se ambos os valores de colunas são menores que media
clientes_com_desconto = (colunas < media).all(axis=1)
clientes_com_desconto

array([False,  True, False,  True,  True])

2.Qual cliente teve pelo menos 2 anos sem cometer acidentes?

In [32]:
# calculando quantos valores 0 tem cada linha
somatoria_acidentes=(acidentes==0).sum(axis=1)
somatoria_acidentes

array([0, 2, 0, 3, 1])

In [33]:
# identificando quais das linhas possuem 2 ou mais zeros
cliente_sem_acidente=somatoria_acidentes>=2
cliente_sem_acidente

array([False,  True, False,  True, False])

3.Uma professora quer que seus alunos apliquem a função (3x+2y+x*y) em um conjunto de dados. Ela dá dois arrays aos estudantes e pede que seja feita essa operação.

In [34]:
# criando o array que correspoderá aos valores de x
x=np.random.randint(20,size=(3,4))
x

array([[ 2,  9,  5, 17],
       [15, 16,  3, 13],
       [14, 14, 11, 16]])

In [35]:
# criando o array que corresponderá aos valores de y
y=np.random.randint(30,size=(3,4))
y

array([[ 5,  0, 17,  2],
       [ 1, 21,  6, 28],
       [ 7, 12, 15,  1]])

In [36]:
# calculando a fórmula
calculo=3*x+2*y+x*y
calculo

array([[ 26,  27, 134,  89],
       [ 62, 426,  39, 459],
       [154, 234, 228,  66]])

4.A mesma professora percebeu que houve um erro em todas as provas dos estudantes e esqueceu de anotar a nota de trabalhos apresentados durante o semestre. Já que foi feito em grupo, ela vai adicionar a mesma nota para todos os estudantes. No array cada estudante representa uma linha e cada coluna uma prova. Adicione para cada prova de cada estudante os valores: 1,2,1.

In [37]:
# criando um array que corresponde às notas de provas dos 25 alunos
provas=np.random.randint(10,size=(25,3))
provas

array([[2, 8, 8],
       [5, 8, 6],
       [9, 7, 5],
       [2, 8, 3],
       [9, 6, 0],
       [5, 3, 3],
       [8, 6, 0],
       [1, 0, 0],
       [4, 7, 8],
       [5, 6, 9],
       [2, 1, 0],
       [2, 7, 3],
       [4, 1, 1],
       [5, 3, 6],
       [9, 8, 1],
       [1, 7, 3],
       [6, 1, 2],
       [7, 3, 2],
       [3, 9, 9],
       [4, 0, 6],
       [6, 7, 3],
       [8, 9, 7],
       [5, 8, 6],
       [9, 7, 1],
       [3, 9, 5]])

In [38]:
# criando um array com as notas dos trabalhos
trabalhos=np.array([1,2,1])
trabalhos

array([1, 2, 1])

In [39]:
# fazendo o cálculo com os dois arrays
nota_final=provas+trabalhos
nota_final

array([[ 3, 10,  9],
       [ 6, 10,  7],
       [10,  9,  6],
       [ 3, 10,  4],
       [10,  8,  1],
       [ 6,  5,  4],
       [ 9,  8,  1],
       [ 2,  2,  1],
       [ 5,  9,  9],
       [ 6,  8, 10],
       [ 3,  3,  1],
       [ 3,  9,  4],
       [ 5,  3,  2],
       [ 6,  5,  7],
       [10, 10,  2],
       [ 2,  9,  4],
       [ 7,  3,  3],
       [ 8,  5,  3],
       [ 4, 11, 10],
       [ 5,  2,  7],
       [ 7,  9,  4],
       [ 9, 11,  8],
       [ 6, 10,  7],
       [10,  9,  2],
       [ 4, 11,  6]])